os: linux
dist: jammy
language: php
php:
  - 8.2

cache:
  npm: true
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn"
  - "./private/node_modules"
  - "./vendor"

before_install:
- phpenv config-rm xdebug.ini

install:
- composer install
- nvm install 20 && nvm use 20
- corepack enable
- cd private && yarn && cd ..

before_deploy:
- yes | gem update --system --force
- gem install bundler
- gem install uri
- gem install logger
- gem install faraday-net_http -v '3.3.0'


stages:
  - name: Lint
    if: branch IS present
  - name: Update Draft Release [DEV]
    if: branch = develop AND type != pull_request
  - name: Update Draft Release [STG]
    if: branch = staging AND type != pull_request
  - name: Update Draft Release [PRD]
    if: branch = main AND type != pull_request

jobs:
  include:
  - stage: Lint
    script:
    - cd private && yarn && yarn build && cd ..
    - composer lint

  - stage: Update Draft Release [DEV]
    script:
    - cd private && yarn && yarn build && cd ..
    - zip -r ../humanity-content-security-policy-develop.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md
    deploy:
      provider: releases
      token:
        secure: "FmtBRWIjCSzuagV1BIOX/R8kCQH9psh5tcLTKq5hD2k+OXs5KoQlVe9uiT7qawyHItW6jkRZgj7aURFrqDpw/+yjjMuLY3IUoYSXLmN5jlBQbe9zUJfSHUxRGAkfmR+KSMAOn9jbJLHQWpHtRJ/OQa6kG7kwmqIfKNBohDF3RsI+ds9RrC5gK/e2k4qJ+7I7A59mDBNehRDa/J6Joy3RD5hnq2PRU3czWJ2I6io9K6arOL6gK0FqhMg5V/qdQb6FuspyPPOheBFJDPaOzKnpKjShdUMXYVCwAVgoNE+Pj3VerMA032gcgQyid84y62PFt+90NIuWkw/8/stjIZnD0/L7zXWG29aeS4cGqpUEBK7WLDqu8oDE7vDNqe6t/ul7QVDPyVTK2rf3xHmHGOwrf4OZZmLoafj4g9V9iauTBHqv38ZwbNZL4AzQAOLmFkGX1MTcj0VPj8p+SVgmFfBFKgXLZM7aJiQ6L1R5ZuurEfmFU+uOshy8mHN36r9QsqLSqdk//KIfgXFGgmBh/UmDU6M+GYhjK1Yq3EZEVCfHn1+meeqCEzS7ADfiNi5DOQXMXnXbQyy8kHvK7Y57cioMUEVrC3+b0zVN1rPSTJu0W53JKEkDDO5ZlofVDOVILHEPyL5xtSkjmqyVIBkvBNqUtFJtvmyDiXGldsOe7deSBiU="
      file: "../humanity-content-security-policy-develop.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-content-security-policy
        branch: develop

  - stage: Update Draft Release [STG]
    script:
    - cd private && yarn && yarn build && cd ..
    - zip -r ../humanity-content-security-policy-staging.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md
    deploy:
      provider: releases
      token:
        secure: "FmtBRWIjCSzuagV1BIOX/R8kCQH9psh5tcLTKq5hD2k+OXs5KoQlVe9uiT7qawyHItW6jkRZgj7aURFrqDpw/+yjjMuLY3IUoYSXLmN5jlBQbe9zUJfSHUxRGAkfmR+KSMAOn9jbJLHQWpHtRJ/OQa6kG7kwmqIfKNBohDF3RsI+ds9RrC5gK/e2k4qJ+7I7A59mDBNehRDa/J6Joy3RD5hnq2PRU3czWJ2I6io9K6arOL6gK0FqhMg5V/qdQb6FuspyPPOheBFJDPaOzKnpKjShdUMXYVCwAVgoNE+Pj3VerMA032gcgQyid84y62PFt+90NIuWkw/8/stjIZnD0/L7zXWG29aeS4cGqpUEBK7WLDqu8oDE7vDNqe6t/ul7QVDPyVTK2rf3xHmHGOwrf4OZZmLoafj4g9V9iauTBHqv38ZwbNZL4AzQAOLmFkGX1MTcj0VPj8p+SVgmFfBFKgXLZM7aJiQ6L1R5ZuurEfmFU+uOshy8mHN36r9QsqLSqdk//KIfgXFGgmBh/UmDU6M+GYhjK1Yq3EZEVCfHn1+meeqCEzS7ADfiNi5DOQXMXnXbQyy8kHvK7Y57cioMUEVrC3+b0zVN1rPSTJu0W53JKEkDDO5ZlofVDOVILHEPyL5xtSkjmqyVIBkvBNqUtFJtvmyDiXGldsOe7deSBiU="
      file: "../humanity-content-security-policy-staging.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-content-security-policy
        branch: staging

  - stage: Update Draft Release [PRD]
    script:
    - cd private && yarn && yarn build && cd ..
    - zip -r ../humanity-content-security-policy.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md
    deploy:
      provider: releases
      token:
        secure: "FmtBRWIjCSzuagV1BIOX/R8kCQH9psh5tcLTKq5hD2k+OXs5KoQlVe9uiT7qawyHItW6jkRZgj7aURFrqDpw/+yjjMuLY3IUoYSXLmN5jlBQbe9zUJfSHUxRGAkfmR+KSMAOn9jbJLHQWpHtRJ/OQa6kG7kwmqIfKNBohDF3RsI+ds9RrC5gK/e2k4qJ+7I7A59mDBNehRDa/J6Joy3RD5hnq2PRU3czWJ2I6io9K6arOL6gK0FqhMg5V/qdQb6FuspyPPOheBFJDPaOzKnpKjShdUMXYVCwAVgoNE+Pj3VerMA032gcgQyid84y62PFt+90NIuWkw/8/stjIZnD0/L7zXWG29aeS4cGqpUEBK7WLDqu8oDE7vDNqe6t/ul7QVDPyVTK2rf3xHmHGOwrf4OZZmLoafj4g9V9iauTBHqv38ZwbNZL4AzQAOLmFkGX1MTcj0VPj8p+SVgmFfBFKgXLZM7aJiQ6L1R5ZuurEfmFU+uOshy8mHN36r9QsqLSqdk//KIfgXFGgmBh/UmDU6M+GYhjK1Yq3EZEVCfHn1+meeqCEzS7ADfiNi5DOQXMXnXbQyy8kHvK7Y57cioMUEVrC3+b0zVN1rPSTJu0W53JKEkDDO5ZlofVDOVILHEPyL5xtSkjmqyVIBkvBNqUtFJtvmyDiXGldsOe7deSBiU="
      file: "../humanity-content-security-policy.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-content-security-policy
        branch: main
