on:
  push:
    branches: [develop]

jobs:
  build:
    uses: ./.github/workflows/step-build.yml
    with:
      stage: ${{ github.ref_name }}
  prepare:
    uses: ./.github/workflows/step-prepare.yml
    needs: [build]
    with:
      stage: ${{ github.ref_name }}
      asset: humanity-content-security-policy-${{ github.ref_name }}.zip
